# Generated by Django 2.2.4 on 2020-05-13 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20200511_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='user',
            new_name='complainer',
        ),
    ]
